### ISSUE TITLE
Tic Tac Toe - toggle function between 'X' and 'O' not working

### ISSUE THREAD

**Issue by HoldenMills** [ga-wdi-boston/independent-work#1]
My javascript is as follows;

 $(document).ready(function() {
  $(".board").on("click",":button",function() {
    var game = {
      board: [ ' ' , ' ' , ' ' , ' ' , ' ' , ' ' , ' ' , ' ' , ' ' ],
      token: 'X'
    };

```
var markCell = function markCell (element) {
  updateBoard($(element).data('cell'));
  // updateUi(element);
  console.log(token);
};

var updateBoard = function updateBoard (index) {
  game.board[index] = game.token;
  console.log(game.token);
};

var updateUi = function updateUi (element) {
  $(element).html(token);
  console.log(token);
};

var toggleTurn = function toggleTurn (element) {
  game.token === 'X' ? game.token = 'O' : game.token = 'X';
};
updateUi(event.target);
markCell(event.target);
toggleTurn(event.target);
```

  });
});

And my board;

<div class="board" id='grid'>
    <button data-cell="0" ></button>
    <button data-cell="1" ></button>
    <button data-cell="2" ></button>
    <button data-cell="3" ></button>
    <button data-cell="4" ></button>
    <button data-cell="5" ></button>
    <button data-cell="6" ></button>
    <button data-cell="7" ></button>
    <button data-cell="8" ></button>
  </div>

When I click on a square it gets marked with an X but does not switch to a O.

**Comment by HoldenMills** [comment]
<div class="board" id='grid'>
    <button data-cell="0" ></button>
    <button data-cell="1" ></button>
    <button data-cell="2" ></button>
    <button data-cell="3" ></button>
    <button data-cell="4" ></button>
    <button data-cell="5" ></button>
    <button data-cell="6" ></button>
    <button data-cell="7" ></button>
    <button data-cell="8" ></button>
  </div>
 Forgot to add the board.

**Comment by HoldenMills** [comment]
``` html
<div class="board" id='grid'>
    <button data-cell="0" ></button>
    <button data-cell="1" ></button>
    <button data-cell="2" ></button>
    <button data-cell="3" ></button>
    <button data-cell="4" ></button>
    <button data-cell="5" ></button>
    <button data-cell="6" ></button>
    <button data-cell="7" ></button>
    <button data-cell="8" ></button>
  </div>
```

**Comment by HoldenMills** [comment]
``` javascript
$(document).ready(function() {
$(".board").on("click",":button",function() {
var game = {
board: [ ' ' , ' ' , ' ' , ' ' , ' ' , ' ' , ' ' , ' ' , ' ' ],
token: 'X'
};

var markCell = function markCell (element) {
  updateBoard($(element).data('cell'));
  // updateUi(element);
  console.log(token);
};

var updateBoard = function updateBoard (index) {
  game.board[index] = game.token;
  console.log(game.token);
};

var updateUi = function updateUi (element) {
  $(element).html(token);
  console.log(token);
};

var toggleTurn = function toggleTurn (element) {
  game.token === 'X' ? game.token = 'O' : game.token = 'X';
};
updateUi(event.target);
markCell(event.target);
toggleTurn(event.target);
});
});

```

**Comment by tdyer** [comment]
Did you try putting a breakpoint in the chrome debugger. Put the breakpoint in click handler.

**Comment by HoldenMills** [comment]
That was it.  Thanks!
