### ISSUE TITLE
Handlebars mini lession

### ISSUE THREAD

**Issue by LaurenGrant** [ga-wdi-boston/independent-work#10]
I have watched some of those youtube handlebars videos and am still not clear on how to create those templates in my html for project 2. Are we going to have a mini lesson from an instructor on this today? That would be very helpful.

**Comment by gaand** [comment]
Did you  just watch or did you also code along?

**Comment by LaurenGrant** [comment]
I did both yesterday. Watched a few videos on it. At the end of the day yesterday Tom asked if people in the class would benefit from a 45min lesson from an instructor on handlebars and the majority said yes. I am wondering if we will be having that lesson today.

**Comment by LaurenGrant** [comment]
But yes, I have watched that video and I did code along.
