### ISSUE TITLE
Logged in user sessions not being stored?

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/independent-work#11]
Currently, I am working on a button that will only display the logged in user's posts. The API, handlers, and back end seem to be functioning properly but here are the critical parts:

Handler:

``` javascript
// all logged in user posts
    else if (location.hash === '#user-posts') {
      switchView('view-all');
      api.getLoggedUserPosts(function(err, data) {
        if(err) {
          console.error(err);
          return;
        }
        var html = allPostTemplate(data);
        $('#view-all').html(html);
      });
    }
```

API:

``` javascript
getLoggedUserPosts: function getLoggedUserPosts(callback) {
    this.ajax({
      method: 'GET',
      url: this.backend + '/posts/user',
      contentType: 'application/json; charset=utf-8'
    }, callback);
  },
```

The issue seems to be that despite logging in from the main page, when I make an attempt to view the logged in user's posts, I receive the error "Log in first" from my controller:

``` javascript
      if(!req.user) {
        var err = new Error("Log in first.");
        return next(err);
      }
```

Does this have something to do with Chrome or cookie settings? I think that might be the case, because the route works fine in Postman.

**Comment by srhoulam** [comment]
It was a matter of using `$.ajaxSetup` to set `xhrFields.withCredentials` to `true` in the correct location.
