### ISSUE TITLE
sign-up errors

### ISSUE THREAD

**Issue by drewster317** [ga-wdi-boston/independent-work#14]
I cannot figure out why my ...

```
$('#signup-form').on('submit', function(e) {
      e.preventDefault();
      var credentials = wrap('credentials', form2object(this));
      projApi.register(credentials, function(error, data) {
        console.log(data);
        var token = data.user.token;
        var user_id = data.user.id;
        var comment = "";
        var profileData = {'profile': {first_name, last_name, comment, user_id}};
        console.log(JSON.stringify(profileData, null, 4));
        projApi.createProfile(profileData, token, callback);
      });
```

..is giving me trouble. Will not let me sign-up. It was working fine before so I feel like it is some small oversight but I need another set of eyes. Element inspector is telling me it is....

```
projApi.register(credentials, function(error, data) {
        console.log(data);
        var token = data.user.token;
        var user_id = data.user.id;
```

**Comment by gaand** [comment]
You need to check to see if `error` is set.  If it is, nothing will work that involves. `data`.

**Comment by drewster317** [comment]
error is set but it seems to be sending data to the back end but the back-end isn't working? The server is running. :-)

**Comment by drewster317** [comment]
Ok. Postgres wasn't on. That's why I just needed a "second set of eyes."
