### ISSUE TITLE
handlebar help with input data

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/independent-work#15]
I have the new div and the static content rendering on the page, but not the name data that is coming out of the variable.

**Comment by srhoulam** [comment]
Can you give more detail? Are you using handlebars? What does said name data look like? Etc.

**Comment by LaurisaNeuwirth** [comment]
using the following handlebars template that I put in my index.html:



 <script id="name-template" type="x-handlebars-template">
 <p>Hello {{name}}</p>
 </script>

</head>
<body>

<div id='name_message'></div>

 The List of Shoes:
 <ul class='shoesNav'></ul>

 <script type="text/javascript" src="jquery.js"></script>
 <script type="text/javascript" src="handlebars.js"></script>
 <script type="text/javascript" src="main.js"></script>
</body>
</html>

Here is my mani.js file - the problem is the page prints "Hello" but not the name

// *\* NAME PORTION **

// 1) Get the HandlerTemplate
var theNameTemplateScript = $("#name-template").html();

// 2) Get the function that will generate HTML
var theNameTemplateFunction = Handlebars.compile(theNameTemplateScript);

 // 3) Create some data to insert into Handlebars template
// var namesData = [{name: 'Noelle'},
// {name: 'Luisa'},
// {name: 'Walter'}
// ];

var namesData = [{name: 'Noelle'}];

// 4) Generate HTML using the function created by 'compile'
var nameListHTML = theNameTemplateFunction(namesData);

// Append this HTML into a div with id of name_message
$('#name_message').append(nameListHTML);

**Comment by srhoulam** [comment]
It's that you're passing in an array of objects (in the variable `namesData`). Pass in just the object `{name: 'Noelle'}`.

**Comment by LaurisaNeuwirth** [comment]
Now that you have the code can we go thru it together? I think the point is to type back if its a fast fix. 

I did give the name data as:  var namesData = [{name: 'Noelle'}];

**Comment by srhoulam** [comment]
As it turns out, this is a fast fix. Replace that line with this:

`var namesData = {name: 'Noelle'};`

**Comment by LaurisaNeuwirth** [comment]
okay.
