### ISSUE TITLE
populating with all sites (no login needed)

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/independent-work#16]
I want anyone to be able to see all the sites show up when they click the See All button on the home page. I'm wondering what I'm missing here: 

from handlebars-template.js:

var siteIndexTemplate = Handlebars.compile($('#site-index').html());

$('#all-sites').click(function(e){
  $('#my-sites').hide();
  $('#main').hide();
  $('#login-reg').hide();
  $('#create-sites').hide();
  $.ajax({
    method: "GET",
    url: "https://localhost:3000",
    dataType: "json"
  }).done(function(data){
    var siteIndexTemplate = Handlebars.compile($('#site-index').html());
    var siteHTML = siteIndexTemplate({site:data});
    $('#populate-sites').html('');
    $('#populate-sites').append(siteHTML);
  }).fail(function(data){
    console.error(data);
  });
});

from my index.html: 

```
        <div id="all-sites">
        <h2>My sites</h2>
        <ul id="populate-sites"></ul>
         <script id="site-index" type="text-x-handlebars-template">
            {{#each site}}
            <div>
              <h2>${{name}}</h2>
              <h3>${{neighborhood}}</h3>
              <p>${{description}}</p>
              <p>Scale: ${{scale}}</p>
              <p>Level of coverage from the elements: ${{coverage}}</p>
              <p>Level of activity: ${{busy}}</p>
            </div>
            {{/each}}
         </script>
        </div>
```

**Comment by srhoulam** [comment]
Do you get any error messages?

**Comment by gaand** [comment]
You're requesting the root route.  Is that what you intended?  Do you see anything in the console from your `console.error`?

**Comment by sarabrentmccoy** [comment]
Ok, I'm closing this and will reopen later but I have a more pressing issue.
