### ISSUE TITLE
Cannot find the syntax error in this

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/independent-work#17]
Thinking of switching over to handlebars, let me know if that will help this issue.

When trying to load the index.html I get this in the browser console

script.js:130 Uncaught SyntaxError: missing ) after argument list

this is my click handler

$("#get-beer").on('click', function(e) {
        e.preventDefault();
        $('#beer-list').html('')
        var token = $('.token').val();
        var data = [];
        on_tap_api.get_beers(token, function(err, data) {
          if (err) {
            console.log(err);
            return;
          } else {
            $.each(data.beers, function(index, element) {
              $('#beer-list').append("<li>""Beer Name: " + data.name.toString() + "   " + "Brewery: " data.brewery.toString() + "   " + "Style: " + data.style.toString() + "    " + "ID: " + data.id.toString() "</li>");
          }
        })
      };
    });

**Comment by gaand** [comment]
Does jshint say anything?  This sort of issue is what it's for.

**Comment by jcmeyer10** [comment]
It's patchy on my SublimeText, been using BracketHighlighter.  Now on to browser based solutions.  This is what I got from JSlint

http://www.jslint.com/

Expected ')' to match '(' from line 12 and instead saw 'data'.

```
$("#get-beer").on('click', function(e) {
    e.preventDefault();
    $('#beer-list').html('');
    var token = $('.token').val();
    var data = [];
    on_tap_api.get_beers(token, function(err, data) {
      if (err) {
        console.log(err);
        return;
      } else {
        $.each(data.beers, function(index, element) {
          $('#beer-list').append("<li>" + "Beer Name: " + data.name.toString() + "   " + "Brewery: " data.brewery.toString() + "   " + "Style: " + data.style.toString() + "    " + "ID: " + data.id.toString() + "</li>");
      }
    })
  };
});
```

**Comment by srhoulam** [comment]
It's your `$.each` call. It doesn't close its brackets.

**Comment by jcmeyer10** [comment]
Needed to start small and list one attribute, then add on when I had the syntax down.
