### ISSUE TITLE
Registration just broke, getting 404 error

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/independent-work#18]
I changed my proj 2 back from heroku to localhost. 
Is this the correct syntax?

**Comment by LaurisaNeuwirth** [comment]
honeyAPI.server = 'http://localhost:5000';

**Comment by LaurisaNeuwirth** [comment]
It was working yesterday bit I don't think I saved my changes before I left. Will you come over so I can get the app functioning again? I am in the middle of adding Edit functionality.

**Comment by srhoulam** [comment]
Your back-end will run on port 3000, not 5000.

**Comment by srhoulam** [comment]
If that doesn't work, I'll come investigate with you.

**Comment by LaurisaNeuwirth** [comment]
I dont understand. Please come and look at my files. I am talking about my front end app.js.

**Comment by LaurisaNeuwirth** [comment]
I think we need to look at them together.
