### ISSUE TITLE
Front end error that might be causing handlebars to not work.

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/independent-work#2]
When I click my "all posts" and send a request to get all the posts on my backend, the object I receive is fine, but the page doesn't render the posts at all. Whenever I do this, in the terminal that I'm running `rubys` in to host the front end on `localhost:5000` the following error appears:

```
[2015-12-07 14:45:03] ERROR `/css/bootstrap.min.css.map' not found.
localhost - - [07/Dec/2015:14:45:03 EST] "GET /css/bootstrap.min.css.map HTTP/1.1" 404 295
- -> /css/bootstrap.min.css.map
```

I think it might be what is causing handlebars to choke, but I' not certain.

Thanks,

-Teo

**Comment by tdyer** [comment]
Put a breakpoint in the callback that will return all posts. See what is returned from the server, it should be json for all posts.

**Comment by TeoPaolucci** [comment]
Found out this error isn't relevant to my issue, closing.
