### ISSUE TITLE
Trying to Create sites. 

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/independent-work#20]
Creating a site works in curl. 
I have a form on my front end where I ask for all the same parameters as I did in curl, but I'm getting this error on my backend server. No errors in the browser.

Started POST "/sites" for ::1 at 2015-12-08 16:21:23 -0500
Processing by SitesController#create as HTML
  Parameters: {"site"=>{}}
  User Load (0.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "c23be386342a30e7c7a1695d47d2ed4d"]]
Completed 400 Bad Request in 21ms (ActiveRecord: 4.4ms)

ActionController::ParameterMissing (param is missing or the value is empty: site):
  app/controllers/sites_controller.rb:62:in `site_params'
  app/controllers/sites_controller.rb:27:in`create'

  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (4.4ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.0ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (51.4ms)

**Comment by srhoulam** [comment]
It had to do with forms and permitting parameters.
