### ISSUE TITLE
Having issues with delete

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/independent-work#21]
When trying to delete from my list I get the following error.

XMLHttpRequest cannot load http://localhost:3000/groceries. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 404.
main.js:262 Object {jqxher: Object, status: "error", error: ""}

Here is my ajax...

``````
deleteGroceries: function(token, callback) {
        this.ajax({
            method: 'DESTROY',
            url: this.url + '/groceries',
            headers: {
                Authorization: 'Token token=' + token
            },
            dataType: 'json'
        }, callback);```

Here is my click handler...
```$('#activity-table').on('click', function(e){
        e.preventDefault();
        var target = e.target;
        // id = $target.parent().parent().data('id');
        // if($target.hasClass("delete")){
        //     console.log("deleting ", id);
            target.remove();

            smart_grocery.deleteGroceries(groceryApp.token, function(err){
                console.log(err);
            });
        // }else if($target.hasClass("edit")){
        //     console.log("editing ", id);


        // $('#update-activity-popup').modal('hide');
        // $('.modal-backdrop').remove();
        // $('#show-activity-list').hide();

});
});```

Here is my controller in rails ...

``````

def destroy
    grocery = Grocery.find(params[:id])
    grocery.destroy
  end

```

Don't know where I am wrong.
```

**Comment by srhoulam** [comment]
It was a matter of tweaking an AJAX request, putting data-id attributes on HTML elements, and tweaking a back-end controller. Now delete and create actions are working properly.
