### ISSUE TITLE
UserID not being attached to New Beer and Vice Versa

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/independent-work#22]
The whole goal is to delete and update beers looking them up by id.  I also want to be able to attach beers to users so they can see only the beers they added.  Gone through the rails repos but still having trouble.  Thanks in advance for any help.

This is my schema.  Added foreign key references on both sides.  Said they each have many.  

`````` javascript
ActiveRecord::Schema.define(version: 20151208221009) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "beers", force: :cascade do |t|
    t.string   "name"
    t.string   "brewery"
    t.string   "style"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer  "user_id"
  end

  add_index "beers", ["user_id"], name: "index_beers_on_user_id", using: :btree

  create_table "users", force: :cascade do |t|
    t.string   "email",           null: false
    t.string   "token",           null: false
    t.string   "password_digest", null: false
    t.datetime "created_at",      null: false
    t.datetime "updated_at",      null: false
    t.integer  "beer_id"
  end

  add_index "users", ["beer_id"], name: "index_users_on_beer_id", using: :btree
  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["token"], name: "index_users_on_token", unique: true, using: :btree

  add_foreign_key "beers", "users"
  add_foreign_key "users", "beers"
end```

Models:

#
class Beer < ActiveRecord::Base
  has_many :users
end

#
class User < ActiveRecord::Base
  include Authentication

  has_many :beers
end

I feel like it might have something to do with the Controllers but I am not sure.  Have been looking online but feel like I am not asking the question the right way.
``````

**Comment by jrhorn424** [comment]
http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to

**Comment by srhoulam** [comment]
Jeff, how you achieve this in ActiveRecord is something you may want to ask someone else on the instructional team, but if looks like you're trying to have beers refer to the user who created them. If that's true, read on.

In order to achieve that, you don't need to add a reference to your user table, only the beers table. Effectively, this is a _users have many beers, beer belongs to one user_ relation. This requires only a column (call it `addedBy`, maybe) on the beers table that references users.

**Comment by jcmeyer10** [comment]
Thanks for the help!  Used some teamwork and spoke with Edie and we realized while different in content, the structure of our apps is similar.  Consulted with how she set up her relationships, mirroring what Saad said.  Then changed this in my beer controller to reflect the fact a current user is creating the beer.  This allowed me to achieve the goals of allowing the logged in user to show their list only, and attaching a user id to a created beer in active record.
