### ISSUE TITLE
Adding omniauth to my authentication

### ISSUE THREAD

**Issue by gracenjambi** [ga-wdi-boston/independent-work#23]
I am working through a tutorial on adding omniauth when using devise gem for my authentication.

I need a second set of eyes on setting up omni auth such that a user is able to authenticate using google or facebook when logging in to my application.

**Comment by gaand** [comment]
These two repos may help:
https://github.com/lynndylanhurley/devise_token_auth
https://github.com/lynndylanhurley/j-toker

**Comment by gracenjambi** [comment]
Thank you I will review them and ask for clarification if I need any. Thank you

**Comment by gracenjambi** [comment]
I am trying to delete the down migration but have not been able to. I found this using

rake db:migrate:status

I have done rake db:rollback, rake db:schema:dump,  rake db:schema:load, rake db:reset, rake db:drop, rake db:create

nothing works please help.

## Status   Migration ID    Migration Name

   up     20151208175848  Create crops
   up     20151208181249  Devise create users
   up     20151208182938  Add columns to users
  down    20151209185623  Devise token auth create [user class]s

**Comment by gaand** [comment]
Closing based on chat with Grace.
