### ISSUE TITLE
Update form not using ajax, changing url to query instead.

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/independent-work#24]
I have an update post form with a submit button supposedly hooked up with ajax:

``` javascript
$('#update-submit').on('submit', function(e) {
    e.preventDefault();
    var post = form2object(event.target);
    var postID = $('#update-ID').val();
    api.updatePost(postID, post, function(err, data) {
      if(err) {
        console.error(err);
        return;
      }
      switchView('view-one');
      var newPostID = data._id;
      api.getSinglePost(newPostID, onePostCallback);
    });
  });
```

``` javascript
updatePost: function updatePost(id, content, callback) {
    this.ajax({
      method: 'PATCH',
      url: this.backend + '/posts/article/' + id,
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(content),
      dataType: 'json'
    }, callback);
  }
```

But every time I click the `#update-submit` button, instead of sending an ajax request, it refreshes the page with a query in the URL.
`localhost:5000/?title=<updated title>&body=<updated body>`

**Comment by gaand** [comment]
The event is on the form, not the button.  So you need to use the form's id.

**Comment by TeoPaolucci** [comment]
Thanks. I'll close this once I get it working. I was just working on another project while I waited for some help so i'm just going to finish my train of thought.
