### ISSUE TITLE
Showing my sites -- a handlebars issue, I think.

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/independent-work#25]
```
        <div id="my-sites">
        <h2>My sites</h2>
        <ul id="populate-sites"></ul>
         <script id="site-index" type="text-x-handlebars-template">
            {{#each site}}
            <div>
              <h2>${{name}}</h2>
              <h3>${{neighborhood}}</h3>
              <p>${{description}}</p>
              <p>Scale: ${{scale}}</p>
              <p>Level of coverage from the elements: ${{coverage}}</p>
              <p>Level of activity: ${{busy}}</p>
            </div>
            {{/each}}
         </script>
        </div>
```

When I show this div (and hide the others) by clicking "My sites" in my sidebar, I hope to show the sites that the logged-in user has created. This is what I have in my handlebars-template.js: 

```
var siteIndexTemplate = Handlebars.compile($('#site-index').html());

$('#my-sites-show').click(function(e){
  $('#all-sites').hide();
  $('#my-sites').show();
  $('#main').hide();
  $('#login-reg').hide();
  $('#create-sites').hide();
  $.ajax({
    method: "GET",
    url: "https://localhost:3000",
    dataType: "json"
  }).done(function(data){
    var siteIndexTemplate = Handlebars.compile($('#site-index').html());
    var siteHTML = siteIndexTemplate(data);
    $('#populate-sites').html('');
    $('#populate-sites').append(siteHTML);
  }).fail(function(data){
    console.error(data);
  });
});
```

The div loads (so the button is working), but it remains unpopulated (just says My Sites at the top). What am I missing?

**Comment by srhoulam** [comment]
I helped Sarabrent to the point that she can almost display a listing of sites that were created by the user who issued the request. She just needs a way to access the current user's database id to complete it.

**Comment by gaand** [comment]
Access the id in the client or the rails api?  If in the api, `current_user`, if set, contains `id` and if sites are associated with a user, should also contain `sites`.  `current_user` will be set if the client sends a valid token in the Authorization header.

**Comment by sarabrentmccoy** [comment]
In the rails API. Where would I be finding this?

**Comment by sarabrentmccoy** [comment]
In the rails API

**Comment by sarabrentmccoy** [comment]
I think current_user is set in the user_serializer, and its scope is that of the user its set to (which includes id), but I'm not sure if this is what you're referring to?

**Comment by gaand** [comment]
From the `SitesController` In the `index` action you can user `current_user` to retrieve all of that users sites (assuming you added the appropriate relationships to the User model).

**Comment by sarabrentmccoy** [comment]
We made it into a different action (mine) and then added this to the routes.rb

get '/sites/mine', to: 'sites#mine'

```

  def index 
    if params[:neighborhood] then
      @sites = Site.where(neighborhood: params[:neighborhood])
    elsif params[:coverage] then
      @sites = Site.where(coverage: params[:coverage])
    elsif params[:busy] then
      @sites = Site.where(busy: params[:busy])
    else
      @sites = Site.all
    end 
    render json: @sites 
  end

  def mine
    @sites = Site.find(user_id: current_user.id) # get current user's id somehow
  end
```

**Comment by gaand** [comment]
Please past the user model.

**Comment by sarabrentmccoy** [comment]
```
class User < ActiveRecord::Base
  include Authentication

  has_many :my_sites, class_name: 'Site'
  has_many :votes
  has_many :sites, through: :votes
end
```

**Comment by gaand** [comment]
To get all of the current user's sites, you should be able to user `current_user.my_sites`.

**Comment by sarabrentmccoy** [comment]
In the mine action?

**Comment by gaand** [comment]
Yes. That will be more clear.  You'll also have to call render from that action.

**Comment by sarabrentmccoy** [comment]
```
def mine
    @sites = current_user.my_sites
    render json: @sites
  end
```

**Comment by sarabrentmccoy** [comment]
Did that, got further than before (actually started GET!), new error: 

Started GET "/sites/mine" for ::1 at 2015-12-09 15:09:52 -0500
Processing by SitesController#mine as HTML
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 3ms (Views: 1.7ms | ActiveRecord: 0.0ms)

**Comment by sarabrentmccoy** [comment]
Is this a token thing? I'm doing all the token things I know how to do in Postman after logging in and it says I'm unauthorized to GET at /sites/mine

**Comment by gaand** [comment]
It's most likely a token thing.
