### ISSUE TITLE
Issue with comment controller (error message inside)

### ISSUE THREAD

**Issue by francescadal** [ga-wdi-boston/independent-work#26]
Started POST "/comments" for ::1 at 2015-12-09 09:57:43 -0500
  ActiveRecord::SchemaMigration Load (3.4ms)  SELECT "schema_migrations".\* FROM "schema_migrations"
Processing by CommentsController#create as _/_
  Parameters: {"post"=>"hello"}
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 21ms (Views: 20.6ms | ActiveRecord: 0.0ms)

**Comment by srhoulam** [comment]
Solved the issue of passing the authorization token across pages. Also got the controller into a working state. Now all that's left is massaging the client-side data into the format the server wants before making the AJAX request.
