### ISSUE TITLE
Delete Function works but invokes Create function on completion of callback processing

### ISSUE THREAD

**Issue by bbarbersox** [ga-wdi-boston/independent-work#27]
Have both create and delete buttons attached to the same form.  Both are working.  But on completion of delete processing the create function is invoked and a new record is created.  Struggling to understand why?

**Comment by jcmeyer10** [comment]
Hope I can help!  Is there a reason why you have them in the same form?  If not, then wrap them up in two different forms, one for each.  I think what is happening is, when you hit the button, it's taking everything in the form and completing it's task.  In this case a delete, then a create.  What does the created object look like?

Also, sorry if I got your hopes up when you saw a little number next to this tab and thought an instructor replied

**Comment by jcmeyer10** [comment]
Also, sorry if I got your hopes up when you saw a little number next to this tab and thought an instructor replied

**Comment by gaand** [comment]
What event fires delete and create?  Please paste the lines of JavaScript that contain the call to the `on` jQuery method.

**Comment by srhoulam** [comment]
We worked on event handlers, handlebars templates, and various complications.
