### ISSUE TITLE
(Project 3) Heroku issue: Cannot Upload file post deployment

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/independent-work#28]
We can can log and register but not upload.  We check the logs and saw something about "Status Not Defined".  Allowing third party cookies in browser.

Not sure where to go from here.

Kayla has to leave between 2:15 and 2:30.

**Comment by gaand** [comment]
Let's meet in classroom 3 in 3 minutes.

**Comment by jcmeyer10** [comment]
ok!

**Comment by jcmeyer10** [comment]
We are running into CORS issues when trying to test locally.  Should we wait on Kayla to try this again?We do not want to change anything that might endanger another Heroku upload.

**Comment by gaand** [comment]
Did restarting mongo help with the delayed login?

**Comment by srhoulam** [comment]
Your application now works after reworking the heroku deployment branch. I have witnessed it working.
