### ISSUE TITLE
Having trouble with pulling ObjectID for a Delete

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/independent-work#29]
Here is the error in rails server: ActionController::RoutingError (No route matches [DELETE] "/beers")

I think there is a problme is a user has many beers and I do not route through users to destroy beers?

Here is my HTML form:

``````
<div class="col-sm-6 col-md-4 col-lg-2">
   <h2>Delete A Beer</h2>
         <p>
               <form id="delete-beer">
                  <input name="beer-id" type="text" placeholder="Beer ID">
                  <input name="delete-beer" type="submit" value="Submit">
                   <input class="token" name="token" type="hidden">
                  <input class="beerid" name="beerid" type="hidden">
               </form>
        </p>
</div>```

Here is my AJAX request
```delete_beer: function (token, id, callback) {
    this.ajax({
    method: 'DELETE',
      url: this.url + '/beers/' + id,
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json; charset=utf-8',
      data: JSON.stringify(id),
      dataType: 'json'

    }, callback);
    console.log(id);
  }
};```

Here is my clickhandler 
```  $("#delete-beer").on('submit', function(e) {
    e.preventDefault();
    var token = $('.token').val();
    var beerid = $('#delete-beer').val();
    console.log(beerid);
    on_tap_api.delete_beer(token, beerid, function(err, data) {
      if (err) {
        console.log(err);
        return;
      } else {
    $('#delete-beer').each(function(){
            this.reset();
          });
      $.each(beerid, function(index, element) {
      $('#beer-list').remove(element.name);
          });
        }
      });
    });```

Here is the browser console log 
``````

script.js:135 
on_tap_api.js:100 
:3000/beers/:1 DELETE http://localhost:3000/beers/ 404 (Not Found)
script.js:139 Object {jqxher: Object, status: "error", error: "Not Found"}```

**Comment by gaand** [comment]
Your route is probably /delete/:id (use `rake routes` to check).  So you need to add an id at the then end of the path for it to work.

**Comment by jcmeyer10** [comment]
Edie and I are having this same problem.  Just been a long day.

these are my beer routes.  I am trying to get the id attached to the url.  Best I have done is attach the user id and [object%20object].  I have console logged everything I could and tried 50 different combinations.  

beers GET    /beers(.:format)          beers#index
          POST   /beers(.:format)          beers#create
 new_beer GET    /beers/new(.:format)      beers#new
edit_beer GET    /beers/:id/edit(.:format) beers#edit
     beer GET    /beers/:id(.:format)      beers#show
          PATCH  /beers/:id(.:format)      beers#update
          PUT    /beers/:id(.:format)      beers#update
          DELETE /beers/:id(.:format)      beers#destroy

**Comment by gaand** [comment]
grab correct `id` using jQuery:

``` js
$('#form-id > input[name="item-id"]').val();
```

grab correct model using ActiveRecord

``` ruby
@item = current_user.items.find(params[:id])
```
