### ISSUE TITLE
Log out not working

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/independent-work#3]
I click on the log out button and get the following (why is this saying login-submit).

Also when I check the DOM I get the following.

Uncaught TypeError: cb is not a function. (But it is a function in my ajax).

localhost - - [07/Dec/2015:14:49:47 EST] "GET /?email=123%40123.com&password=123&login-submit=Log+In HTTP/1.1" 200 6950
http://localhost:5000/ -> /?email=123%40123.com&password=123&login-submit=Log+In
localhost - - [07/Dec/2015:14:49:47 EST] "GET /css/stylesheet.css HTTP/1.1" 200 4902
http://localhost:5000/?email=123%40123.com&password=123&login-submit=Log+In -> /css/stylesheet.css
localhost - - [07/Dec/2015:14:49:47 EST] "GET /js/api.js HTTP/1.1" 200 5303

**Comment by tdyer** [comment]
Using the chrome debugger, put a breakpoint in the logout button handler step through and make sure the correct Ajax request is being made to the backend.

**Comment by pguzman26** [comment]
I got the following after the breakpoint. Something with the header.

SyntaxError: Failed to execute 'setRequestHeader'

**Comment by gaand** [comment]
Please post the code that handles the log out event.

**Comment by pguzman26** [comment]
Here is my log out event.

 $('#logout-button').on('click', function(e) {
            e.preventDefault();
            var credentials = wrap('credentials', form2object(e.target));
            smart_grocery.logout(credentials, function(err, data) {
                if (err) {
                    console.log(err);
                } else {
                token = data.user.token;
                var user_id = data.user.id;
                console.log(data);
                $('.logInForm').show();
                $('#register_form').show();
                $('#logout-button').hide();
                $(".grocery").hide();

**Comment by gaand** [comment]
Is the logout button in a form?  If so, are you suppressing the form submit event?

**Comment by pguzman26** [comment]
log out button is not in a form yet. But I do have type="submit". Please see below.

`<button id="logout-button" class="btn btn-warning btn-lg" type="submit">Log Out</button>`

**Comment by gaand** [comment]
That seems like a likely source of the problem.  Change the `type` to `button` (for now) and see if that helps.

**Comment by pguzman26** [comment]
I changed it to type button and am having the same issue.

**Comment by srhoulam** [comment]
Pablo, did you do a hard-refresh of your front-end after making the change?

**Comment by pguzman26** [comment]
Yes I did.

Pablo Guzman

pabloguzman26@yahoo.com mailto:pabloguzman26@yahoo.com
407-243-8014

**Comment by pguzman26** [comment]
Fixed the issue by setting var groceryApp = groceryApp || {}; globally and then calling it on my log out. Was not passing the right arguments to the log out callback. Was not saving the user id after login so that it can be used in the log out. 

$('#logout-button').on('click', function(e) {
            e.preventDefault();
            var credentials = wrap('credentials', form2object(e.target));
            smart_grocery.logout(groceryApp.user_id, groceryApp.token, function(err, data) {
                if (err) {
                    console.log(err);
                } else {
                console.log("Logged out");
            }
            });
        });
