### ISSUE TITLE
after update, my bundle install won't run and xcode wont reinstall

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/independent-work#33]
I ran out od room on my disk yesterday so I freed some up.
When I went to reinstall xcode, it just hangs in the App Store.

I tried to bundle install and got 'bundle install
Could not locate Gemfile or .bundle/ directory'

I am worried my update might have messed up my install fest environment.

**Comment by tdyer** [comment]
Postgresql was not running. Now OK.
