### ISSUE TITLE
Having issues with update

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/independent-work#34]
When trying to run my click handler for update, for some reason it does not want to execute my modal.

Here is what my click handler is supposed to do ..... 

the data-toggle='modal' data-target='#update-acivity-popup' should pop up. 

$('#update-activity').on('click', function(e) {
        e.preventDefault();
        var target = e.target;
        var id = $(target).parent().parent().data('id');
        smart_grocery.updateGroceries(groceryApp.token, function(err, data){
          console.log('data is' + data);
          var groceries = data.groceries;
          var listHTML = "";
          groceries.forEach(function(grocery){
            listHTML += "<tr data-id=\"" + grocery.id + "\"><td>" + grocery.name + "</td>" + "<td><button class='edit btn btn-primary' data-toggle='modal' data-target='#update-acivity-popup'>Edit</button><button class='delete'>Delete</button></td></tr>";
          });
        });
        $('#update-activity-popup').modal('hide');
        $('.modal-backdrop').remove();
    });

**Comment by tdyer** [comment]
The JS main.js has lots of indentation issues, handlers being defined inside handlers. I showed him how to fix a couple of handler functions, annotating the end of functions, better indentations,..
