### ISSUE TITLE
Meets expectations?

### ISSUE THREAD

**Issue by TeoPaolucci** [ga-wdi-boston/independent-work#37]
I would like if an instructor could look at my project 2 and project 3 and let me know if what I have complete so far "meets expectations" and if not, what needs to be done to achieve that.

**Comment by tdyer** [comment]
I will look at this Teo and get back to you today.

**Comment by TeoPaolucci** [comment]
My work isn't hosted yet, it might be better if I showed you what I have on my own computer.

**Comment by TeoPaolucci** [comment]
Speaking of which, I need help hosting my projects when possible/after I get them to meet expectations.
