### ISSUE TITLE
Getting Undefined for Quanitity

### ISSUE THREAD

**Issue by jcmeyer10** [ga-wdi-boston/independent-work#38]
It goes in right in the backend

SQL (0.5ms)  INSERT INTO "beers" ("name", "brewery", "style", "quantity", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["name", "pgj"], ["brewery", "gjop"], ["style", "gpj"], ["quantity", "9"], ["user_id", 14], ["created_at", "2015-12-10 17:28:04.398579"], ["updated_at", "2015-12-10 17:28:04.398579"]]

The object comes back with a quantity when I console log my AJAX call and when I console log the data coming in from my click handler.

But when I console log data coming in from my Get Beer click handler, it doesn't include quantity and displays undefined on the list in the HTML:  Beer: pgj Brewery: gjop Style: gpj Quantity: undefined ID: 97

and in the console Object {name: "ghi", brewery: "gio", style: "gpojg", created_at: "2015-12-10T17:24:45.717Z", id: 95}

**Comment by gaand** [comment]
Are you using a serializer?  Does it include quantity?

**Comment by jcmeyer10** [comment]
Going over project 3 with Tom and will check after.  I think that could be
the problem.

**Comment by jcmeyer10** [comment]
Yes it was, welcome back to Rails.

For anyone who references this:
If you are getting the right data being created on the front end, and the right data being put into the database, CHECK YOUR SERIALIZER!
