### ISSUE TITLE
GET request  is not working

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/independent-work#4]
When trying to do a GET request from my frontend I get the following. I am getting a 401 unauthorized.

Processing by GroceriesController#show as HTML
  Parameters: {"id"=>"e31615c3865399dd1e5bf7085d192243"}
  User Load (0.2ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "[object Object]"]]
  Rendered text template (0.0ms)
Filter chain halted as :authenticate rendered or redirected
Completed 401 Unauthorized in 2ms (Views: 0.7ms | ActiveRecord: 0.2ms)

**Comment by tdyer** [comment]
Looks like you're login is not working. Make sure that the callback function for the login is setting the authentication token in your front-end. 

This authentication token should be sent on subsequent request from the frontend to the backend.

**Comment by pguzman26** [comment]
I am able to login successfully. Please see below.

---

Started OPTIONS "/login" for ::1 at 2015-12-07 15:17:07 -0500

Started POST "/login" for ::1 at 2015-12-07 15:17:07 -0500
Processing by AuthController#login as HTML
  Parameters: {"credentials"=>{"email"=>"123@123.com", "password"=>"[FILTERED]"}}
  User Load (0.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."email" = $1 LIMIT 1  [["email", "123@123.com"]]
  SQL (1.4ms)  UPDATE "users" SET "token" = '635a372f28fe4301874a882c732ae3d3', "updated_at" = '2015-12-07 20:17:07.489013' WHERE "users"."id" = $1  [["id", 3]]
Completed 200 OK in 71ms (Views: 0.4ms | ActiveRecord: 1.7ms)

## Here is my code

 $('#login-form').on('submit', function(e) {
        e.preventDefault();
        var credentials = wrap('credentials', form2object(e.target));
        smart_grocery.login(credentials, function(err, data) {
            if (err) {
                console.log(err);
            } else {
                token = data.user.token;
                var user_id = data.user.id;
                console.log(data);
                $('.logInForm').hide();
                $('#register_form').hide();
                $('#logout').show();
                $(".grocery").show();
            }

```
    });
```

**Comment by gaand** [comment]
Is `token` defined somewhere outside of your submit handler?

**Comment by pguzman26** [comment]
I tried to define it outside my login function. But don't know the correct way to make it work so that I can call it while login in or out for example.

**Comment by gaand** [comment]
Creating **one** global object to hold state isn't a bad idea.

At the top of each JavaScript file you can add:

``` js
var groceryApp = groceryApp || {};
```

Then you can test and set properties of that, i.e.

``` js
  // in login handler
  groceryApp.token = data.user.token;
```

and

``` js
if (groceryApp.token) {
  // logged in
} else {
  // not logged in
}
```

Please let me know if I should explain in more detail.

**Comment by pguzman26** [comment]
Please elaborate more. Are you guys sure we are talking about  my GET request? Because this seems to sound like my other open ticket regarding my log out.

**Comment by tdyer** [comment]
Was sending the wrong arguments to the function to render his groceries.

**Comment by pguzman26** [comment]
Needed to pass in groceryApp and token. GroceryApp is my globally declared empty object.

global var object....

var groceryApp = groceryApp || {};

click handler....

$('#show-activity-list').on('click', function(e) {
        e.preventDefault();
        var item = {
            name: "name"
        };
        smart_grocery.showGroceries(groceryApp.token, function(err, data){
            console.log('data is' + data);
