### ISSUE TITLE
Having issue with update

### ISSUE THREAD

**Issue by pguzman26** [ga-wdi-boston/independent-work#41]
I am trying to make my update work. 

I am trying to pass an id to it, by selecting the previous row and it is  not working. My front end is talking to my back end. Please see the following code.

 $('#update-activity').on('submit', function(event) {
        event.preventDefault();

```
    smart_grocery.updateGroceries(groceryApp.token, wrap('grocery', form2object(event.target)), function(err, data) {
        console.log(err, data);
        var groceries = data.groceries;
        var listHTML = "";
        $('#activity-table tr:last').after(groceries.forEach(function(grocery) {
            listHTML += "<tr data-id=\"" + grocery.id + "\"><td>" + grocery.name + "</td>" +
                "<td><button class='edit' >Edit</button><button class='delete'>Delete</button></td></tr>";

        }));
        $('#activity-table').append(listHTML);
    });
```

**Comment by gaand** [comment]
Please post the code for the updateGroceries method.

**Comment by pguzman26** [comment]
This is my ajax call

```
updateGroceries: function(token, id, grocery, callback) {
    this.ajax({
        method: 'PATCH',
        url: this.url + '/groceries/' + id,
        headers: {
            Authorization: 'Token token=' + groceryApp.token
        },
        contentType: 'application/json',
        data: JSON.stringify(grocery),
        dataType: 'json'
    }, callback);
```

},

**Comment by pguzman26** [comment]
Here are my error messages.

Uncaught ReferenceError: listHTML is not defined(anonymous function) @ main.js:285m.event.dispatch @ jquery.js:4670r.handle @ jquery.js:4338
jquery.js:9664 OPTIONS http://localhost:3000/groceries/[object%20Object] send @ jquery.js:9664m.extend.ajax @ jquery.js:9215smart_grocery.ajax @ api.js:29smart_grocery.updateGroceries @ api.js:148(anonymous function) @ main.js:274m.event.dispatch @ jquery.js:4670r.handle @ jquery.js:4338
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/groceries/[object%20Object]. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 400.
api.js:32 Uncaught TypeError: cb is not a function

**Comment by gaand** [comment]
Your passing too few arguments to `updateGroceries`.

``` js
smart_grocery.updateGroceries(groceryApp.token, wrap('grocery', form2object(event.target)), function(err, data) {
```

versus

``` js
updateGroceries: function(token, id, grocery, callback) {
```

You're not including the `id` in the call

**Comment by pguzman26** [comment]
I added the id and am still getting the following.

Uncaught ReferenceError: listHTML is not defined(anonymous function) @ main.js:285m.event.dispatch @ jquery.js:4670r.handle @ jquery.js:4338
jquery.js:9664 OPTIONS http://localhost:3000/groceries[object%20Object] send @ jquery.js:9664m.extend.ajax @ jquery.js:9215smart_grocery.ajax @ api.js:29smart_grocery.updateGroceries @ api.js:148(anonymous function) @ main.js:274m.event.dispatch @ jquery.js:4670r.handle @ jquery.js:4338
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/groceries[object%20Object]. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 400.
api.js:32 Uncaught TypeError: cb is not a function

**Comment by pguzman26** [comment]
Here is what I have added.

```
$('#update-activity').on('submit', function(event) {
    event.preventDefault();

    smart_grocery.updateGroceries(groceryApp.token, wrap('grocery', id, form2object(event.target)), function(err, data) {
        console.log(err, data);
       var groceries = data.groceries;
        var listHTML = "";
        groceries.forEach(function(grocery) {
            listHTML += "<tr data-id=\"" + grocery.id + "\"><td>" + grocery.name + "</td>" +
                "<td><button class='edit' >Edit</button><button class='delete'>Delete</button></td></tr>";

        });
        $('#activity-table').append(listHTML);
    });
```

**Comment by gaand** [comment]
You put it in the wrong place.  After you grab the id from the form it should look like:

``` js
smart_grocery.updateGroceries(groceryApp.token, id, wrap('grocery', form2object(event.target)), function(err, data) {
```

**Comment by pguzman26** [comment]
I am getting a 404 error.

PATCH http://localhost:3000/groceries1 404 (Not Found)
main.js:275 Object {jqxher: Object, status: "error", error: "Not Found"} undefined
main.js:276 Uncaught TypeError: Cannot read property 'groceries' of undefined

**Comment by gaand** [comment]
Is this still the line from `updateGroceries`?

``` js
        url: this.url + '/groceries/' + id,
```

There's a slash missing from the error you posted.  `http://localhost:3000/groceries1` should be `http://localhost:3000/groceries/1`.

**Comment by pguzman26** [comment]
It has been fixed. When I try to edit potato, potato has an id of 132. But when I click on update it has an id of 1.

**Comment by pguzman26** [comment]
Sorry when I do a read on my list potato has an id of 132 but when I click on edit it has an id of 1

**Comment by pguzman26** [comment]
Still having issues, it is patching and I am still getting back an object of null.  Please see below.

main.js:288 Object {id: 150, name: null, created_at: "2015-12-11T18:19:19.146Z", updated_at: "2015-12-11T18:31:43.125Z"}
main.js:289 Uncaught TypeError: Cannot read property 'forEach' of null

**Comment by gaand** [comment]
Please post the controller code that handle the update.  And what the rails server shows.
