### ISSUE TITLE
using query string to get data based on provider gives me entire set of data instead

### ISSUE THREAD

**Issue by bbarbersox** [ga-wdi-boston/independent-work#42]
Am using a query to get a subset of data (based on name of provider).  Instead of getting the subset all the data is being returned.

Below is the rails data controller using 

//////////////////////////////
class ActivitiesController < OpenReadController

  before_action :set_activity, only: [:update, :destroy]
  # get s list of all activities
  def index
    @activities = Activity.all
    render json: @activities
  end

  # show a single activity
  def show
    if params[:id]
      @activity = Activity.find(params[:id])
    else
        if params[:provider]
          @activity = Activity.find(params[:provider])
        else
          @activity = Activity.find(params[:dov])
        end
    end

```
render json: @activity
```

  end

  #create a new activity
  def create
    @activity = current_user.activities.new(activity_params)

```
if @activity.save
  render json: @activity, status: :created, location: @activity
else
  render json: @activity.errors, status: :unprocessable_entity
end
```

  end

  def update
    if @activity.update(activity_params)
      head :no_content
    else
      render json: @activity.errors, status: :unprocessable_entity
    end
  end

  # DELETE /activities/1
  def destroy
    # @activity = Activity.find(params[:id]
    activity = Activity.find(params[:id])
    # Activity.delete
    activity.destroy

```
head :no_content
```

  end

  def set_activity
    @activity = current_user.activities.find(params[:id]) # makes this activity the users activity
  end

  def activity_params
    params.require(:activity).permit(:name, :provider, :prono, :prostreet, :procity, :prostate, :zip, :dov, :tov, :length, :participant, :user_id)
  end

  private :set_activity, :activity_params
end
////////////////////////////

Below is the ajax call to the get the only the provider data from the server.
////////////////
SearchActivityByProvider: function (provider, token, callback) {
    debugger;
    this.ajax({
      method: 'GET',
      url: this.ttt + '/activities/?provider=' + provider,
      headers: {
        Authorization: 'Token token=' + token
      },
      dataType: 'json'
    }, callback);
  },
/////////////////////////////

**Comment by gaand** [comment]
Your path likely matches the `index` action (which is as it should be - run `rake routes` to see the mappings).  You'll need to move the code that restricts by provider to that method and use `where` rather than `find` to restrict the results.

**Comment by bbarbersox** [comment]
Below is the output from the rake routes command.  It appears changes to my routes file has created a activities_provider line instead of a new method for show under the activities controller.  I am confused. 
//////////////////////////////////////
~/wdi/project2-api (master)$ rake routes
           Prefix Verb   URI Pattern                                 Controller#Action
         register POST   /register(.:format)                         auth#register
            login POST   /login(.:format)                            auth#login
                  DELETE /logout/:id(.:format)                       auth#logout
       properties GET    /properties(.:format)                       properties#index
                  POST   /properties(.:format)                       properties#create
         property GET    /properties/:id(.:format)                   properties#show
                  PATCH  /properties/:id(.:format)                   properties#update
                  PUT    /properties/:id(.:format)                   properties#update
                  DELETE /properties/:id(.:format)                   properties#destroy
activity_provider GET    /activities/:activity_id/provider(.:format) activities#show
       activities GET    /activities(.:format)                       activities#index
                  POST   /activities(.:format)                       activities#create
     new_activity GET    /activities/new(.:format)                   activities#new
    edit_activity GET    /activities/:id/edit(.:format)              activities#edit
         activity GET    /activities/:id(.:format)                   activities#show
                  PATCH  /activities/:id(.:format)                   activities#update
                  PUT    /activities/:id(.:format)                   activities#update
                  DELETE /activities/:id(.:format)                   activities#destroy
            users GET    /users(.:format)                            users#index
                  POST   /users(.:format)                            users#create
             user GET    /users/:id(.:format)                        users#show
                  PATCH  /users/:id(.:format)                        users#update
                  PUT    /users/:id(.:format)                        users#update
                  DELETE /users/:id(.:format)                        users#destroy
///////////////////////////////////////

**Comment by gaand** [comment]
Moved provider logic to index action and used where to restrict results.
