### ISSUE TITLE
Deleting a site

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/independent-work#43]
What am I missing? Nothing registering on the server. In the console, only says "Navigated to http://localhost:5000/?id=18"

from sites controller: 

```
  def destroy
    site = Site.find(params[:id])
    site.destroy
    flash[:notice] = "page successfully deleted!!!!!"
    redirect_to(:action => 'index')

    head :no_content
  end
```

from the api.js:

```
  deleteSite: function (token, site, callback) {
    this.ajax({
      method: 'DELETE',
      url: this.url + '/delete', 
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json, charset=utf-8',
      data: JSON.stringify(deleted_site)
    })
  }

  $('#delete-site').on('submit', function(e) {
    e.preventDefault();

    var deleted_site = wrap('site', form2object(e.target));
    proj_twoapi.deleteSite(token, site, function(err, data) {
      if(err) {
        console.log(err)
      } else{
        console.log(data);
      }
    });

    return false;
  });
```

I'm wondering if maybe it's something wrong with my route because when I try to delete a site by ID 17 (and click the Delete Site button, I'm sent here: http://localhost:5000/?id=17 (and it reloads the home page, and doesn't delete the site). Here's my route: 

```
delete '/delete', to: 'auth#delete'
```

Here's the html for the Delete Site div

```
<div id="delete-sites">
              <h2>Delete a site</h2>
              <div>
              <form>
                Site ID: 
                <input name="id" type='text' placeholder='ID'>
                <button id="delete-site" type="submit" class="btn btn-success">Delete site</button>
              </form>
              </div>
            </div>
```

**Comment by gaand** [comment]
You just need to append the id to the path for DELETE.  You don't need to pass any data.

**Comment by sarabrentmccoy** [comment]
So just change the path in routes.rb to 

```
delete '/delete/:id', to: 'auth#delete'
```

?

**Comment by sarabrentmccoy** [comment]
Changed the path in routes.rb to 

```
delete '/delete/:id', to: 'auth#delete'
```

Deleted passed data in api.js

```
  $('#delete-site').on('submit', function(e) {
    e.preventDefault();

    var deleted_site = wrap('site', form2object(e.target));
    proj_twoapi.deleteSite(token, site, function(err) {
      if(err) {
        console.log(err)
      } else{
        console.log("You deleted that!");
      }
    });

    return false;
  });
```

**Comment by sarabrentmccoy** [comment]
Same behavior

**Comment by gaand** [comment]
It's probably already that (run `rake routes` to see).

You need to change

``` js
        url: this.url + '/delete', 
```

to 

``` js
      url: this.url + '/delete' + id, 
```

where `id` is the id of the site you want to delete.  Don't pass any data.

**Comment by gaand** [comment]
Delete these lines from `deleteSite` method

``` js
      contentType: 'application/json, charset=utf-8',
      data: JSON.stringify(deleted_site)
```

**Comment by sarabrentmccoy** [comment]
Ok thanks. Made those fixes. rake routes: 

```
Prefix Verb   URI Pattern           Controller#Action
```

  register POST   /register(.:format)   auth#register
     login POST   /login(.:format)      auth#login
sites_mine GET    /sites/mine(.:format) sites#mine
    delete DELETE /delete(.:format)     auth#delete
     users GET    /users(.:format)      users#index
           POST   /users(.:format)      users#create
      user GET    /users/:id(.:format)  users#show
           PATCH  /users/:id(.:format)  users#update
           PUT    /users/:id(.:format)  users#update
           DELETE /users/:id(.:format)  users#destroy
     votes POST   /votes(.:format)      votes#create
     sites GET    /sites(.:format)      sites#index
           POST   /sites(.:format)      sites#create
      site GET    /sites/:id(.:format)  sites#show
           PATCH  /sites/:id(.:format)  sites#update
           PUT    /sites/:id(.:format)  sites#update
           DELETE /sites/:id(.:format)  sites#destroy

**Comment by sarabrentmccoy** [comment]
A lot of those seem messy...

**Comment by gaand** [comment]
Those look pretty standard. Is delete working?

**Comment by sarabrentmccoy** [comment]
Not yet

**Comment by gaand** [comment]
Are you getting any error messages?

**Comment by sarabrentmccoy** [comment]
None on the server, and console says "Navigated to http://localhost:5000/?id=18" (when I try to delete Site w ID 18

**Comment by gaand** [comment]
What's the id of your form?  I think you may have added the event handler to a button on the form, not the form itself.

**Comment by sarabrentmccoy** [comment]
There was an inconsistency there -- the handler went for id delete-site, and the div had id delete-sites. But now: 

Started OPTIONS "/delete/16" for ::1 at 2015-12-11 11:59:43 -0500


Started DELETE "/delete/16" for ::1 at 2015-12-11 11:59:43 -0500

ActionController::RoutingError (No route matches [DELETE] "/delete/16"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'


  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.6ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb (1.9ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.6ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (6.5ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (76.1ms)

**Comment by sarabrentmccoy** [comment]
There was a naming inconsistency. Fixed it. ID points to whole div. Console says: 

DELETE http://localhost:3000/delete/16 
localhost/:1 XMLHttpRequest cannot load http://localhost:3000/delete/16. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 404.
proj2_api.js:8 Uncaught TypeError: cb is not a function

**Comment by sarabrentmccoy** [comment]
Server: 

Started OPTIONS "/delete/16" for ::1 at 2015-12-11 12:10:21 -0500

Started DELETE "/delete/16" for ::1 at 2015-12-11 12:10:21 -0500

ActionController::RoutingError (No route matches [DELETE] "/delete/16"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in`call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in`call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in`call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in`call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in`process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in`call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.4ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_route.html.erb (0.7ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/routes/_table.html.erb (1.6ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (65.3ms)

**Comment by sarabrentmccoy** [comment]
An interesting thing is that it says the path is /delete/16 no matter which site ID # I enter/try to delete
