### ISSUE TITLE
update site error

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/independent-work#46]
getting a 404 error on server and in console 

Started PATCH "/sites/undefined" for ::1 at 2015-12-11 14:42:41 -0500
Processing by SitesController#update as HTML
  Parameters: {"site"=>{"update-id"=>"15", "description"=>"hello"}, "id"=>"undefined"}
  User Load (0.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "8345a2854e36b223f300bf76d7f76f58"]]
  Site Load (0.5ms)  SELECT  "sites".\* FROM "sites" WHERE "sites"."user_id" = $1 AND "sites"."id" = $2 LIMIT 1  [["user_id", 16], ["id", 0]]
Completed 404 Not Found in 9ms (Views: 1.1ms | ActiveRecord: 0.8ms)

Where should I look? 

```
  $('#update-sites form').on('submit', function(e) {
    e.preventDefault();

    var updateid = $('#update-sites>input[name="update-id"]').val();
    var updated_site = wrap('site', form2object(e.target));
    console.log(updated_site);
    proj_twoapi.updateSite(token, updateid, updated_site, function(err, data) {
      if(err) {
        console.log(err)
      } else{
        console.log(data);
      }
    });

    return false;
  });
```

```
  updateSite: function (token, id, updated_site, callback) {
    this.ajax({
      method: 'PATCH',
      url: this.url + '/sites/' + id,
      headers: {
        Authorization: 'Token token=' + token
      },
      contentType: 'application/json, charset=utf-8',
      data: JSON.stringify(updated_site),
      dataType: 'json',
    }, callback);
  },
```

from sites controller: 

```
  def update
    @site = Site.find(params[:id])
    render json: site_params
    if @site.update(site_params)
      render json: @site
    else
      render json: @site.errors, status: :unprocessable_entity
    end
  end
```

udpate form div: 

```
            <div id="update-sites">
            <form>
              <div>
                <h2>Update a site description</h2>
                <div>
                  <p style="font-weight: bold; margin-top: 10px;">Site ID:</p>
                  <input class="id-field" name="update-id" type='text' style="margin-bottom: 10px;" placeholder="ID">
                </div>
                <div>
                  <p style="font-weight: bold; margin-top: 10px;">Description:</p>
                  <input class="description-field" name="description" type='text' style="margin-bottom: 10px;" placeholder=" What's this place like? What's it good for?">
                </div>
              </div>
              <button style="margin-top: 10px;" id="new-site" type="submit" class="btn btn-success">Update site</button>
            </form> 
            </div>
```

**Comment by sarabrentmccoy** [comment]
I've changed this code around a bit: 
Getting 500 error

```
  $('#update-sites form').on('submit', function(e) {
    e.preventDefault();

    var id = $('#update-sites input').val();
    // var updateid = $('#update-sites>input[name="update-id"]').val();
    var updated_site = wrap('site', form2object(e.target));
    console.log(updated_site);
    proj_twoapi.updateSite(token, id, updated_site, function(err, data) {
      if(err) {
        console.log(err)
      } else{
        console.log(data);
      }
    });

    return false;
  });
```

**Comment by sarabrentmccoy** [comment]
Started PATCH "/sites/15" for ::1 at 2015-12-11 16:03:57 -0500
Processing by SitesController#update as HTML
  Parameters: {"site"=>{"update-id"=>"15", "description"=>"hello hello"}, "id"=>"15"}
  User Load (1.1ms)  SELECT  "users".\* FROM "users" WHERE "users"."token" = $1 LIMIT 1  [["token", "5d32fdd454c63152519c80e1ed68bf35"]]
  Site Load (0.5ms)  SELECT  "sites".\* FROM "sites" WHERE "sites"."user_id" = $1 AND "sites"."id" = $2 LIMIT 1  [["user_id", 16], ["id", 15]]
  Site Load (0.3ms)  SELECT  "sites".\* FROM "sites" WHERE "sites"."id" = $1 LIMIT 1  [["id", 15]]
Unpermitted parameter: update-id
Unpermitted parameter: update-id
   (0.2ms)  BEGIN
  SQL (0.4ms)  UPDATE "sites" SET "description" = $1, "updated_at" = $2 WHERE "sites"."id" = $3  [["description", "hello hello"], ["updated_at", "2015-12-11 21:03:57.407169"], ["id", 15]](0.3ms)  COMMIT
Completed 500 Internal Server Error in 60ms (Views: 2.2ms | ActiveRecord: 2.8ms)

AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".):
  app/controllers/sites_controller.rb:45:in `update'

  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (5.5ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.8ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.8ms)
  Rendered /usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (54.9ms)

**Comment by sarabrentmccoy** [comment]
Here is the updated HTML (now input name=id)

```
<div id="update-sites">
            <form>
              <div>
                <h2>Update a site description</h2>
                <div>
                  <p style="font-weight: bold; margin-top: 10px;">Site ID:</p>
                  <input class="id-field" name="id" type='text' style="margin-bottom: 10px;" placeholder="ID">
                </div>
                <div>
                  <p style="font-weight: bold; margin-top: 10px;">Description:</p>
                  <input class="description-field" name="description" type='text' style="margin-bottom: 10px;" placeholder=" What's this place like? What's it good for?">
                </div>
              </div>
              <button style="margin-top: 10px;" id="new-site" type="submit" class="btn btn-success">Update site</button>
            </form> 
            </div>
```

**Comment by gaand** [comment]
Please post the code form the controller

**Comment by sarabrentmccoy** [comment]
```
  def update
    @site = Site.find(params[:id])
    render json: site_params
    if @site.update(site_params)
      render json: @site
    else
      render json: @site.errors, status: :unprocessable_entity
    end
  end
```

**Comment by gaand** [comment]
You can't call render twice.  The key error is:

```
AbstractController::DoubleRenderError (Render and/or redirect were called multiple times in this action.
```

**Comment by sarabrentmccoy** [comment]
That's it! It's working! Thanks.
