### ISSUE TITLE
Having an Handlebars issue - not invoking handlebars or passing the object

### ISSUE THREAD

**Issue by bbarbersox** [ga-wdi-boston/independent-work#5]
## The handlebars module is below

var activityData = {activity: [ {actTitle: "Fishing with a Mission", actDesc: "Fishing trip for students and Alumni of Boston Higashi School", actDate: "2016-8-15", actTime: "10:00 am"}]};

  var actHandlebars = {
  displayHomepage: function(data){
    console.log('got to actHandlers');
    console.log(data);
    var activitiesTemplate = Handlebars.compile($('#activitiesList').html());
    var newHTML = activitiesTemplate({activity: data});
    $("#putActivitiesList").html(newHTML);
  }
};

actHandlebars.displayHomepage(activityData);
## The script code to invoke the Handlebars routtine in my .html file is below:

<script id="activitiesList" type="text/x-handlebars-template">
        console.log('getting to HandleBars rendering')
        {{#each activity}}
            console.log('got inside Handlebars each loop');
            <div class="overview">
                <p class="main-detail">{{actDate}}</p>
                <p class="sub-detail">{{actTime}}</p>
                <span class="label label-success">Active</span> <span class="label label-info">New</span>
            </div>
            <div class="info">
                <p>{{actTitle}}</p>
                <p>{{actDesc}}</p>
                <a class="btn btn-mini" href="#">Show Details</a>
            </div>
            <div class="clearfix"></div>
        {{/each}}
    </script>

```
<!-- END Handlebars call -->

<!-- handlebars -->
<script src="app/handlebars-v4.0.4.js"></script>

<!--  Local Scripts -->
<script src="app/handlebars_module.js" type = "application/javascript"></script>
```

**Comment by gaand** [comment]
What's returned when you enter `$('#activitiesList').html()` into the console after you load you app?

**Comment by bbarbersox** [comment]
console.log('getting to HandleBars rendering')
        {{#each activity}}
            console.log('got inside Handlebars each loop');
            <div class="overview">
                <p class="main-detail">{{actDate}}</p>
                <p class="sub-detail">{{actTime}}</p>
                <span class="label label-success">Active</span> <span class="label label-info">New</span>
            </div>
            <div class="info">
                <p>{{actTitle}}</p>
                <p>{{actDesc}}</p>
                <a class="btn btn-mini" href="#">Show Details</a>
            </div>
            <div class="clearfix"></div>
        {{/each}}

**Comment by gaand** [comment]
I think you need to use the `log` helper rather than `console.log` in a template, e.g. `{{log 'getting to HandleBars rendering'}}`

See http://handlebarsjs.com/builtin_helpers.html

**Comment by bbarbersox** [comment]
same error when console.log is replaced with {{log}}.  The activity log looks fine.  All the actDate and other variables are undefined.
Below is output from $('#activitiesList').html() ---

"
        {{log 'getting to HandleBars rendering'}}
        {{log activity}}
        {{#each activity}}
            {{log actTitle}}
            <div class="overview">
                <p class="main-detail">{{actDate}}</p>
                <p class="sub-detail">{{actTime}}</p>
                <span class="label label-success">Active</span> <span class="label label-info">New</span>
            </div>
            <div class="info">
                {{log 'getting to HandleBars info rendering'}}
                <p>{{actTitle}}</p>
                <p>{{actDesc}}</p>
                <a class="btn btn-mini" href="#">Show Details</a>
            </div>
            <div class="clearfix"></div>
        {{/each}}
    "

**Comment by bbarbersox** [comment]
Passing in the wrong array of an object, not the object.  When the object is passed to handlebars template it is working.  Thanks.
