### ISSUE TITLE
Missing var of app in app.js

### ISSUE THREAD

**Issue by LaurisaNeuwirth** [ga-wdi-boston/independent-work#7]
I am getting this error in my Proj 2:
Uncaught ReferenceError: honeyApp is not defined       in my app.js file

when it is trying to run:
honeyApp.user = data.user;

I know I had honeyApp defined and set to something in my app.js but it must have gotten deleted. I don't know how to go back in my commits to see it using github. 

I have looked back at some repos from class lectures and I cannot find it. I need some help writing it the right way.

**Comment by LaurisaNeuwirth** [comment]
I mean I know I need to var the honeyApp I just don't know what to set it to so that it refers to the data for the app that is coming in.

**Comment by LaurisaNeuwirth** [comment]
and I know it goes in the app.js file.

**Comment by LaurisaNeuwirth** [comment]
in the api.js file, I have:

var honeyAPI = honeyAPI || {};

and I think honeyApp needs to be defined similarly?

**Comment by gaand** [comment]
Yes. At the top of each JavaScript file.

**Comment by LaurisaNeuwirth** [comment]
I tried var honeyApp = honeyApp || {}; but it broke my register (which worked prior)
POST http://localhost:3000//register 422 (Unprocessable Entity)

**Comment by tdyer** [comment]
Going to take a look at this issue with Laurisa.

**Comment by LaurisaNeuwirth** [comment]
Needed to move it to top of the app.js file.
