### ISSUE TITLE
Showing/hiding divs -- what's missing?

### ISSUE THREAD

**Issue by sarabrentmccoy** [ga-wdi-boston/independent-work#8]
I don't know what I'm missing: I'm trying to set up click handlers that show/hide corresponding divs (login, my sites, etc.) but all the divs are showing, one after the other (none are hidden), and none of the click handlers bring me anywhere. What am I missing? 
# login-reg-show (etc) is an id of the li on which a click brings us to the new div.
# login-reg (etc) is an id of the div to which the click (on the login-reg-show li) brings us.

$('#login-reg-show').click(function(){
    $('#login-reg').show();
    $('#main').hide();
    $('#sites').hide();
});

$('#sites-show').click(function(){
    $('#sites').show();
    $('#main').hide();
    $('login-reg').hide();
});

$('#home-show').click(function(){
    $('#sites').hide();
    $('#main').show();
    $('login-reg').hide();
});

**Comment by gaand** [comment]
Try putting a break point inside the click handler to see if the code you think is running actually is.

From the chrome tools Sources view.

**Comment by sarabrentmccoy** [comment]
I wasn't listing scripts in my index.html in the right order; needed 3rd party first. Was missing reference to one js file.
